Desktop_RWD_version
stenlisuryadinata/mobile_portfolio_test pull request #2
Opened 2023-03-05 02:21 UTC by stenlisuryadinata

Desktop_RWD_version

required change: 
Use media queries to make sure that your website displays correctly on desktop screens.

in the following task: 
the media queries is used to develop desktop RWD version.

2023-03-05 03:46 UTC, emmiiorji requested changes
Hi <STUDENT_MENTION>, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220869680-787a77f7-922b-4e57-8fa4-368533d83b89.gif'/>
</div>

## Good Highlights✔️

- Proper use of media queries to display desktop version
- You have the project image and description alternating as in design


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-05 03:46 UTC, emmiiorji commented on styles_.css
> +}
Kindly ensure that the cards are close to the design as possible. Consider the comparison below:

Your design:
![image](https://user-images.githubusercontent.com/20554583/222940171-e109898a-7090-4403-b3e1-40a36aa74c46.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/222940194-8378ed87-6b15-43c1-bc75-894bad21c88f.png)

2023-03-05 03:46 UTC, emmiiorji commented on styles_.css
> +
Kindly adjust the about myself section to match the design. The languages have icons within the boxes and the horizontal lines below skills and frameworks titles are faded.

Your design:
![image](https://user-images.githubusercontent.com/20554583/222940425-5d6e12d7-c6e2-4957-bf0f-e0d6d214a74d.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/222940430-4872b4bc-1d9a-42bf-84cd-04c951c49649.png)

2023-03-05 03:46 UTC, emmiiorji commented on styles_.css
> +  .mypage-container {
Kindly ensure that the mobile version is responsive until the desktop screen size.

![image](https://user-images.githubusercontent.com/20554583/222940517-955026d0-6cf4-4406-872c-64e05ed32f32.png)

![image](https://user-images.githubusercontent.com/20554583/222940519-05f6060f-e485-498f-84a2-7631695e707d.png)

2023-03-05 08:06 UTC, stenlisuryadinata commented
required changes : 
-that the cards are close to the design as possible. Consider the comparison between figma and the design
-the languages have icons within the boxes and the horizontal lines below skills and frameworks titles are faded
-the mobile version is responsive until the desktop screen size.

in the following task 
-change the cards as per figma 
-the icons are added and the horizontal line are faded as per figma
-the mobile person is responsive until the desktop screen size

2023-03-06 20:21 UTC, bellom approved these changes
@stenlisuryadinata,

### This is a manual review

# Approved :+1:

Cheers and Happy coding!:clap::clap::clap:

2023-03-07 05:06 UTC, stenlisuryadinata commented
Thank you, I really appreciated it

2023-03-07 05:06 UTC, merged